services:

  postgres:
    image: postgres:17
    container_name: neuronix-postgres
    environment:
      POSTGRES_DB: neuronix
      POSTGRES_USER: neuronix
      POSTGRES_PASSWORD: neuronix
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: