spring.application.name=neuronix-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/neuronix
spring.datasource.username=neuronix
spring.datasource.password=neuronix

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.user=neuronix
spring.flyway.password=neuronix

management.endpoints.web.exposure.include=health,info